### ISSUE TITLE
Mismatched last ERA timestamp

### ISSUE THREAD

**Issue by bnulzq** [fluxnet/ONEFlux#54]
I run the pipline from 2018 to 2021, but meet this error at the very end stage (already output the hourly results in 99_ folder)

ONEFluxError: US-ARc mismatched last ERA timestamp expected (202212312330) and found (202112312330)

Zhenqi Luo

**Comment by gilbertozp** [comment]
You can specify the last year for the ERA downscaling passing the parameter --era-ly 2021

**Comment by bnulzq** [comment]
> 

Thank you so much, problem solved!
